version: '3'
services:
  redis:
    build: redis
    ports: 
      - "6379"
  cassandra:
    build: cassandra304
    ports:
      - "9042"
  web:
    build: nodeserver
    ports:
     - "80:3000"
    volumes:
     - .:/usr/src/app
    depends_on:
      - cassandra
      - redis
    command: ["./wait_for_it.sh", "cassandra:9042", "--", "npm", "start"]